### ISSUE TITLE
Octal numerals

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-lang#1058]
The topic of octal notation has recently come up in https://github.com/dhall-lang/dhall-haskell/issues/1988 and https://github.com/dhall-lang/dhall-kubernetes/issues/139.

Particularly for file permissions, it would be useful if `Natural`s could be written in octal notation, e.g. `0o10` for `8`.

For reference, Dhall already supports hexadecimal numerals: https://github.com/dhall-lang/dhall-lang/issues/858

**Comment by jdoss** [comment]
To give another instance of not having octal numerals handled well in Dhall, that isn't related to k8s, I am trying to manage my Fedora CoreOS Configs which are YAML files with Dhall. The [FCCT tool]( https://github.com/coreos/fcct) translates human readable Fedora CoreOS Configs (FCCs) into machine readable Ignition Configs and it expects `mode` directives to be written in octal too. 

Take this for example:

```
variant: fcos
version: 1.1.0
storage:
  files:
    - path: /opt/file
      contents:
        inline: Hello, world!
      mode: 0644
      user:
        id: 500
      group:
        id: 501
```

Converting it to dhall strips the leading zero:

```
cat fcos.yml | yaml-to-dhall 
{ storage.files =
  [ { contents.inline = "Hello, world!"
    , group.id = 501
    , mode = 644
    , path = "/opt/file"
    , user.id = 500
    }
  ]
, variant = "fcos"
, version = "1.1.0"
}
```

If we add the zero back in:
```
{ storage.files =
  [ { contents.inline = "Hello, world!"
    , group.id = 501
    , mode = 0644
    , path = "/opt/file"
    , user.id = 500
    }
  ]
, variant = "fcos"
, version = "1.1.0"
}
```

It produces this error:

```
cat fcos.dhall |dhall-to-yaml


Error: Invalid input

(input):4:15:
  |
4 |     , mode = 0644
  |               ^
unexpected '6'
expecting ',', ->, :, keyword, operator, whitespace, or }
```
