### ISSUE TITLE
YAML output record fields in order for readability

### ISSUE THREAD

**Issue by JohannesRudolph** [dhall-lang/dhall-lang#342]
Suppose I have the following record definitions:

```dhall
{ platform :
    Text
, inputs :
    List ./directory.dhall
, outputs :
    List ./directory.dhall
, params :
    List ./param.dhall
, run :
    { path : Text, args : List Text }
}
```

When I run such a value through `dhall-to-yaml`, I get a YAML that looks like this

```yaml
platform: linux
inputs:
- name: abc
run:
  args:
  - ec
  - |
    cp -r a/* b/
    cd b
outputs:
- name: sources-with-creds
```
Unfortunately the reordering of yaml fields compared to the record definition makes these files a little less readable. Ideally, dhall-to-yaml would have a mode that allows for preservation of field order to make generated yaml a little more human-friendly. This is important when I want my generated YAML to match established conventions or replace existing hand-built YAML with dhall-generated ones without creating crazy diffs. Of course, yaml key order is not important semantically, so this is just about humans reading it.
