### ISSUE TITLE
Question: hash of an expression at evaluation time

### ISSUE THREAD

**Issue by purcell** [dhall-lang/dhall-lang#562]
I have a case where I'm generating application config files using Dhall, and then providing those files to Docker services as Docker "configs". Docker "configs" are immutable, so when the contents of the config files change, the Docker configs must be given a new name, which means it's convenient to use a hash of the content as the nameof each config.

I'd love to be able to get a `Text` value that is the sha256 of the evaluated expression for the content. Is this something that the evaluation model of Dhall would be able to support?

I didn't find a `Text -> Text` hash function in the prelude, and while it would be nice to have the more general `a -> Text`, `Text -> Text` would do the job.

**Comment by singpolyma** [comment]
Such functions would be possible, but I'd want to understand the use case more before adding them as builtins. There's a lot of possible useful data transformations that we can't build in Dhall as-is, but we also don't want to sprout dozens of builtins...

The one thing that may make a -> Hash ok is that we already have functionality to hash a Dhall expression in the standard, so adding that builtin would essentially only involve assigning a name.

**Comment by Gabriel439** [comment]
@purcell: For me the main concern is that this breaks parametricity.  According to parametricity the only functions that can have type `∀(a : Type) → a → Text` are those that ignore their argument and always return some constant string.  We want to preserve parametricity in order to provide stronger guarantees about what functions can do based on their type.

**Comment by purcell** [comment]
> Such functions would be possible, but I'd want to understand the use case more before adding them as builtins. There's a lot of possible useful data transformations that we can't build in Dhall as-is, but we also don't want to sprout dozens of builtins...

Here's an example of the output I need to create for a `docker-compose.yaml`:

```yaml
services:
  nginx-api:
    image: nginx:alpine
    networks:
    - web
    ports:
    - 4080:80
    deploy:
      replicas: 1
    configs:
    - source: nginx_htpasswd_abc1c07eb7cfc092efa752c9ca243b1d
      target: /etc/nginx/nginx-htpasswd
configs:
  nginx_htpasswd_abc1c07eb7cfc092efa752c9ca243b1d:
    file: etc/nginx-htpasswd
```

The above is generated from a Dhall file. The "configs" entry has to have a name that depends on the contents of the associated file. Right now I have a separate shell script which generates separate files containing Dhall expressions for the hash of each config file, so that those separate files can be included in the overall Dhall file. This extra arcane machinery would be redundant if I could directly obtain a hash of the config files' content. It's just a bit clunky.

> For me the main concern is that this breaks parametricity.

This was the kind of concern I was wondering about, yes. I'm personally fine with `Text -> Text`, since the generated file content is always `Text` anyway.
